version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: dinjiggasa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/dinjiggasa?schema=public
      PORT: 3001
      JWT_SECRET: your_random_secret_here
      # Update these to match your server IP or Domain
      FRONTEND_URL: https://deenjiggasa.info
      R2_ACCESS_KEY_ID: a0017ece4e4345c55400f567fb570b20
      R2_SECRET_ACCESS_KEY: 757f18239678408838ad83ffeecccbf33ffaaf06256d00459cabeb3dd9f4c855
      R2_BUCKET_NAME: deenjiggasa
      R2_ACCOUNT_ID: cfa83ebbd807204ffc47084e0880ca94
      R2_PUBLIC_URL: https://pub-bdfe03272733446f8722cd7c4ffc3954.r2.dev
      ZEPTOMAIL_URL: https://api.zeptomail.com/v1.1/email
      ZEPTOMAIL_TOKEN: "Zoho-enczapikey wSsVR60l+ET2WqZ8yGWsdO9rmw9UBAikREws2Abz4yL4F6+Xosc5xBedDQL2TfAbRWA7E2AX8e0vmRoI2zEK3dgtzQ5WCyiF9mqRe1U4J3x17qnvhDzJW2pZlhuBLosJzgRrmGdhGsog+g=="
      ZEPTOMAIL_FROM_ADDRESS: noreply@deenjiggasa.info
      ZEPTOMAIL_FROM_NAME: DinJiggasa
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://deenjiggasa.info/api/v1
    restart: always
    environment:
      # Browser needs to hit the public IP/domain
      NEXT_PUBLIC_API_URL: https://deenjiggasa.info/api/v1
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
